### ISSUE TITLE
automate action definition updates

### ISSUE THREAD

**Issue by krancour** [akuity/kargo-render#150]
Every time we do a release, we need to update `action.yaml` _before_ the semver tag is applied so that the action definition correctly references the new image that _will_ be cut during the release process.

This is "chicken and egg" problem in a certain respect because the update has to happen before the release to reference something that doesn't exist yet, but _will be produced by_ the release.

Currently, this update happens manually, but it's too easy to forget.

I'm thinking through how to deal with this still, but didn't want to lose track of the issue.

**Comment by adithyaakrishna** [comment]
@krancour Can we use the latest tag for the images?
