### ISSUE TITLE
add kargo logo to readme page

### ISSUE THREAD

**Issue by krancour** [akuity/kargo-render#186]
Now that we're officially counting this as a Kargo sub-project, the AI-generated octopus can go and we can slap the Kargo logo on the README -- at least until we get a Kargo Render logo. (If we do.)

Correct logo can be found here: https://github.com/akuity/kargo/blob/main/kargo-logo.png

Layout should be similar to [Kargo's README](https://github.com/akuity/kargo/blob/main/README.md)

**Comment by anevski-stefan** [comment]
@krancour I want to work on this issue, can you assign me?

**Comment by krancour** [comment]
@anevski-stefan all yours!

**Comment by anevski-stefan** [comment]
@krancour There was one PR with these changes, in the first issue there was a need to update the logo and to include the logo, so this is a duplicate one.
