### ISSUE TITLE
governance: remove auto-application of needs/area label

### ISSUE THREAD

**Issue by krancour** [akuity/kargo-render#211]
This project isn't huge, so sometimes it's very tough to slot a particular change into a specific area.

I still like that we have areas that we can use for things that _are_ distinct, like area/release-process for example, but in contrast to Kargo proper, which is a much larger project, I'm not sure if mandating issues to be labeled with an area is buying us much.

@kencochrane tagging you in case you want to fix, but I'm also happy to take it.

**Comment by kencochrane** [comment]
@krancour just so I'm clear you would like to remove the governance bot from this repo?

**Comment by krancour** [comment]
@kencochrane no... I just want to remove the requirement that an area label _must_ be set.

**Comment by kencochrane** [comment]
ok gotcha, I can do that.
