### ISSUE TITLE
Ability to render to local path without commit

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo-render#229]
Spawned from https://github.com/akuity/kargo-render/pull/228

Kargo Render would benefit from an option that skips all commit / PR activity and writes rendered files to stdout or a specified location.

This will enable kargo proper to be able to handle git commit/prs itself, separately from render and do so in a consistent manner when rendering is not used.

**Comment by peschmae** [comment]
That would be a great feature!

It would also enable to use kargo-render with renovate bot and the postUpgrade hook, if one is using just subdirectories for the rendered manifests
