### ISSUE TITLE
Regex Validation for Branch Pattern fails

### ISSUE THREAD

**Issue by stieglma** [akuity/kargo-render#264]
According to the documentation at https://kargo-render.akuity.io/how-to-guides/configuration#keeping-things-dry it should be possible to use patterns for branches. This seems to be broken. I assume this happened already a while ago when schema validation was introduced.

The pattern here: https://github.com/akuity/kargo-render/blob/main/schema.json#L19 definitely can't match something that is a regex itself. As regex is not "mighty" enough to do this in a generic way we need some kind of workaround, I spontaneously think this could be solutions:
- keep the regex pattern as is, if this validation fails, then try to parse the branchname as pattern itself, if that works we might be fine (this solution depends on if the validation errors can be handled separately, otherwise we would try for every config validation, and probably loose some real errors
- change the regex pattern, in a way, that, as soon as something "regexy" appears (a backslash, a bracket) the validation is always ok
- only allow the very specific regex pattern `(\w+)` inside the branchname. This limits the what can be done, but it could still be good enough for what is needed

**Comment by krancour** [comment]
@stieglma there is no regex validation in the "pattern" field. I am guessing you mistakenly put your own regex inside the "name" field.

**Comment by stieglma** [comment]
that's true 🙈 I tried all kinds of things, but it never occurred to me, that the fieldname could be different, I just looked at the value. Thanks for the clarification

**Comment by krancour** [comment]
No worries. It's a separate field for the exact reason you mentioned. Regex isn't mighty enough to validate a regex. 🙂
